[package]
name = "fdo-db"
version = "0.4.13"
edition = "2021"


[dependencies]
anyhow = "1.0"
diesel = { version = "2.1.0", features = ["sqlite", "postgres", "r2d2"] }

fdo-data-formats = { path = "../data-formats", version = "0.4.13" }

[dev-dependencies]
fdo-http-wrapper = { path = "../http-wrapper", version = "0.4.13", features = ["server"] }
openssl = "0.10.55"

[features]
postgres = []
sqlite = []

default = ["postgres", "sqlite"]