on:
  push:
  workflow_dispatch:

name: Continuous Delivery

jobs:
  build:
    runs-on: ubuntu-latest
    environment: continuous_delivery
    env:
      quay_org: fido-fdo

    steps:
    - uses: actions/checkout@v3

    - name: Perform container builds
      id: build
      uses: ./.github/actions/build_containers

    - name: Push serviceinfo-api-server to quay.io
      uses: redhat-actions/push-to-registry@v2
      with:
        registry: "quay.io/kpwrwyfmyzpxupsign"
        image: serviceinfo-api-server
        tags: ${{ steps.build.outputs.tags }}
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_ROBOT_TOKEN }}
